swagger: "2.0"

info:
  title: "Weyland"
  description: "Print Server for [AxiDraw v3](http://axidraw.com/) pen plotter by [Evil Mad Scientist](http://www.evilmadscientist.com/)"
  version: "1"
  contact:  
    name: "Tapani Otala"
    url: "http://github.com/tjotala/weyland"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

schemes:
- "http"

parameters:
  job_id:
    name: job_id
    in: path
    description: Print job ID
    required: true
    type: string

  new_print_job:
    name: new_print_job
    in: body
    description: New print job
    required: true
    schema:
      type: object
      required:
      - svg
      properties:
        name:
          description: "Print job name (default: none)"
          type: string
          required: false
          default: ""
          example: "Test Print"
        svg:
          description: "Print job content (encoded as JSON-safe string)"
          type: string
          format: binary
          example: "see a SVG file"
        convert:
          description: "Convert print job via Inkscape"
          type: boolean
          required: false
          default: false
          example: true

definitions:
  server_configuration:
    title: Server configuration
    type: object
    required:
    - product
    - platform
    - environment
    - time
    - total_space
    - available_space
    properties:
      product:
        description: "Product name"
        type: string
        example: "Weyland/1.0"
      platform:
        description: "Platform type"
        type: string
        example: "Linux raspberrypi 4.9.24-v7+ #993 SMP Wed Apr 26 18:01:23 BST 2017 armv7l GNU/Linux"
      environment:
        description: "Deployment environment"
        type: string
        example: "development"
      time:
        description: "Current server date/time"
        type: string
        format: dateTime
        example: "2017-05-07T21:02:55Z"
      total_space:
        description: "Total space of server print queue"
        type: integer
        minimum: 1
        example: 62385172480
      available_space:
        description: "Available space in servver print queue"
        type: integer
        minimum: 1
        example: 55570456576

  printer_firmware_version:
    title: Printer firmware version
    type: object
    properties:
      version:
        description: "Printer firmware version"
        type: string
        example: "Firmware Version 2.5.1"
    required:
    - version

  print_job:
    title: Print job
    type: object
    properties:
      id:
        description: "Print job identifier (8 hex digits)"
        type: string
        example: "748e80004a66be3d"
      name:
        description: "Print job name"
        type: string
        example: "Test Print"
      size:
        description: "Print job size"
        type: integer
        example: 2904
      status:
        description: "Print job status"
        type: string
        enum:
        - pending
        - converting
        - printing
        - printed
        - failed
        example: "printed"
      created:
        description: "Date/time when print job was first created"
        type: string
        format: dateTime
        example: "2017-05-07T07:00:07Z"
      updated:
        description: "Date/time when print job was last updated"
        type: string
        format: dateTime
        example: "2017-05-07T07:00:14Z"
    required:
    - id
    - name
    - size
    - status
    - created
    - updated
    
  print_jobs:
    title: Print jobs
    type: array
    items:
      $ref: "#/definitions/print_job"

tags:
- name: System
  description: System APIs
- name: Printer
  description: Printer APIs
- name: Jobs
  description: Print Job APIs
  
paths:
  /v1/config:
    get:
      summary: "Returns system configuration information"
      tags:
      - System
      produces:
      - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/server_configuration"

  /v1/ping:
    get:
      summary: "Health check"
      tags:
      - System
      produces:
      - "text/plain"
      responses:
        200:
          description: "OK"
          schema:
            type: string
            example: "ok"

  /v1/quit:
    get:
      summary: "Shutdown server"
      tags:
      - System
      responses:
        204:
          description: "OK"

  /v1/shutdown:
    get:
      summary: "Shutdown appliance"
      tags:
      - System
      responses:
        204:
          description: "OK"

  /v1/printer/version:
    get:
      summary: "Returns printer firmware version"
      description: "This API can be used to test connectivity to the printer."
      tags:
      - Printer
      produces:
      - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/printer_firmware_version"
        504:
          description: "Unable to communicate with printer"

  /v1/printer/pen/up:
    post:
      summary: "Moves printer pen up"
      tags:
      - Printer
      responses:
        204:
          description: "No Content"
        504:
          description: "Unable to communicate with printer"

  /v1/printer/pen/down:
    post:
      summary: "Moves printer pen down"
      tags:
      - Printer
      responses:
        204:
          description: "No Content"
        504:
          description: "Unable to communicate with printer"

  /v1/jobs:
    get:
      summary: "List print jobs"
      tags:
      - Jobs
      produces:
      - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/print_jobs"

    post:
      summary: "Create New Print Job"
      tags:
      - Jobs
      parameters:
      - $ref: "#/parameters/new_print_job"
      produces:
      - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/print_job"

    delete:
      summary: "Delete All Print Jobs"
      tags:
      - Jobs
      responses:
        204:
          description: "OK"

  /v1/jobs/{job_id}:
    get:
      summary: "Get Print Job Information"
      tags:
      - Jobs
      parameters:
      - $ref: "#/parameters/job_id"
      produces:
      - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/print_job"

    delete:
      summary: "Delete Print Job"
      tags:
      - Jobs
      parameters:
      - $ref: "#/parameters/job_id"
      responses:
        204:
          description: "OK"

  /v1/jobs/{job_id}/content:
    get:
      summary: "Get Print Job Content"
      tags:
      - Jobs
      parameters:
      - $ref: "#/parameters/job_id"
      produces:
      - "image/svg+xml"
      responses:
        200:
          description: "OK"
          schema:
            type: file
          headers:
            Content-Disposition:
              description: "Tells the browser to render the content inline"
              type: string
              example: "inline"

  /v1/jobs/{job_id}/print:
    post:
      summary: "Print a Job"
      tags:
      - Jobs
      parameters:
      - $ref: "#/parameters/job_id"
      - convert:
          description: "Convert the print job with Inkscape (overrides original request)"
          name: convert
          in: query
          type: boolean
          required: false
          default: false
          example: true
      produces:
      - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/print_job"
        409:
          description: "print job is already printing"
        429:
          description: "another print job is already printing"
